[package]
name = "edamame_foundation"
version = "0.3.2"
edition = "2021"

[lints.rust]
async_fn_in_trait = "allow"

[features]
disable-grpc = []

[lib]
# Dynamic lib version is not used on apple platforms as it's painful, but we must use it on windows and linux
# We must keep lib if we want to build targets with cargo
# Adding cdylib is required for windows but is messing up the build on macOS and iOS
crate-type = ["staticlib", "lib"]

[dependencies]

# Sentry
sentry = "0.32.1"
sentry-log = "0.32.1"

# Global statics w/ mutex
lazy_static = "1.4.0"
once_cell = "1.19.0"

# JSON
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_with = "3.4.0"
uuid = { version = "1.6.1", features = [
    "v4",                
    "v5",                
    "fast-rng",          
    "macro-diagnostics", 
]}

# Logging
log = "0.4.20"
signal-hook = "0.3"
flexi_logger = "0.27.4"

# gRPC server/client
tonic = { version = "0.10.2", features = ["tls"] }
prost = "0.12.3"
base64 = "0.21.5"

# CLI support
run_script = "0.10.1"
powershell_script = "1.1.0"

# Async
async-trait = "0.1.77"
parking_lot = "0.12.1"
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }

# Advanced time
chrono = { version = "0.4.31", features = ["serde"] }

# Network utils
ipnet = "2.9.0"
# wez-mdns = "0.1.1"
# Our own mdns implementation forked from wez-mdns
wez-mdns = { git = "https://github.com/edamametechnologies/mdns" }

# Misc
rand = "0.8.5"
anyhow = { version = "1.0.79" }
regex = "1.10.2"
sorted-vec = "0.8.3"
encoding_rs = "0.8.33"
libc = "0.2.152"

# Not WASI/WASIX/WASM
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

# Network utils
# See https://github.com/abaumhauer/eui48/issues/29 - warning should be suppressed, but it's not...
eui48 = { version = "1.1.0", features = ["disp_hexstring", "serde"] }
oui = "0.8.1"
ipnet = "2.9.0"

# SSL related deps for iOS/Android (rustls doesn't work on iOS/Android due to missing certs but native-tls does)
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["native-tls", "json"] }

# SSL related deps for not iOS/Android
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
reqwest = { version = "0.11.18", features = ["json"] }

# Not supported on iOS an Android (only implemented in Flutter for those platforms)
[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
network-interface = "1.1.1"

# Libpnet is a dependency that is not working on iOS/Android and depends on WinPcap on windows (that we don't want to ship with the binary)
[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
arp-toolkit = "0.3.2"

# macOS - system-configuration-sys is including a symbol that is rejected by the App Store
[patch.crates-io]
system-configuration = { git = "https://github.com/edamametechnologies/system-configuration-rs" }
system-configuration-sys = { git = "https://github.com/edamametechnologies/system-configuration-rs" }

[build-dependencies]

# protobuf->Rust compiler
tonic-build = "0.10.2"
