[package]
name = "edamame_foundation"
version = "0.3.4"
edition = "2021"

[lints.rust]
async_fn_in_trait = "allow"

[features]
default = ["helper"]
helper = ["tonic", "prost", "tonic-build", "run_script", "powershell_script"] # Include helper related dependencies by default
nohelper = [] # When this feature is enabled, `helper` dependencies are excluded

[lib]
# Dynamic lib version is not used on apple platforms as it's painful, but we must use it on Windows, Linux and Android
# We must keep lib if we want to build targets with cargo
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
edamame_backend = { git = "https://github.com/edamametechnologies/edamame_backend", version = "0.3.3" }

# Sentry
sentry = "0.34.0"
sentry-tracing = "0.34.0"

# Global statics w/ mutex
lazy_static = "1.5.0"
once_cell = "1.19.0"

# Strum
strum = "0.26.3"
strum_macros = "0.26.4"

# JSON
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_with = "3.8.3"
uuid = { version = "1.9.1", features = [
    "v4",                
    "v5",                
    "fast-rng",          
    "macro-diagnostics", 
]}

# Logging
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
tracing-appender = "0.2.3"
humantime = "2.1.0"

# gRPC server/client, marked as optional
tonic = { version = "0.12.1", features = ["tls"], optional = true }
prost = { version = "0.13.1", optional = true }

base64 = "0.22.1"

# CLI support
run_script = { version = "0.10.1", optional = true }
powershell_script = { version = "1.1.0", optional = true }

# Async
async-trait = "0.1.81"
parking_lot = "0.12.3"
futures-util = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }

# Advanced time
chrono = { version = "0.4.38", features = ["serde"] }

# Network utils
ipnet = { version = "2.9.0" }
# mdns discovery that works on all platforms and tolerates foreign language characters
# wez-mdns = "0.1.1"
# Our own mdns implementation forked from wez-mdns
wez-mdns = { git = "https://github.com/edamametechnologies/mdns" }

# Misc
rand = "0.8.5"
anyhow = { version = "1.0.86" }
regex = "1.10.5"
sorted-vec = "0.8.3"
encoding_rs = "0.8.34"
libc = "0.2.155"
thiserror = "1.0.61"

# Not WASI/WASIX/WASM
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

# Network utils
# See https://github.com/abaumhauer/eui48/issues/29 - warning should be suppressed, but it's not...
eui48 = { version = "1.1.0", features = ["disp_hexstring", "serde"] }
oui = "0.8.1"
ipnet = "2.9.0"

# SSL related deps for iOS/Android (rustls doesn't work on iOS/Android due to missing certs but native-tls does)
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
reqwest = { version = "0.12.5", default-features = false, features = ["native-tls", "json", "gzip"] }

# SSL related deps for not iOS/Android
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
reqwest = { version = "0.12.5", features = ["json", "gzip"] }

# Not supported on iOS an Android (only implemented in Flutter for those platforms)
[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
network-interface = "2.0.0"

# Libpnet is a dependency that is not working on iOS/Android and depends on WinPcap on windows (that we don't want to ship with the binary)
[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
arp-toolkit = "0.3.2"

# macOS - system-configuration-sys is including a symbol that is rejected by the App Store
[patch.crates-io]
system-configuration = { git = "https://github.com/edamametechnologies/system-configuration-rs" }
system-configuration-sys = { git = "https://github.com/edamametechnologies/system-configuration-rs" }

# Android
[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2.0"

# iOS or macOS
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
tracing-oslog = "0.1.2"

[dev-dependencies]
serial_test = "3.1.1"

[build-dependencies]

# Conditional compilation for build dependencies
# protobuf->Rust compiler
tonic-build = { version = "0.12.1", optional = true }

