[package]
name = "l7_ebpf_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"] # produce .a archive; build script extracts .o

[dependencies]
aya_ebpf = { package = "aya-ebpf", version = "0.1.1" }

[profile.release]
panic = "abort"