#!/usr/bin/env python3
"""
Encode a CloudModel JSON fallback as a gzip-compressed, XOR-obfuscated
embedded byte array consumable by the obfuscated_cloud_model_fallback!
macro in flodbadd::cloud_model_fallback (and the equivalent module in
edamame_foundation).

Why: the previous shape (`pub static FOO_DB: &str = r#"..."#;`) embeds the
JSON as a single contiguous UTF-8 block in the binary's rodata section.
strings(1) and Microsoft Defender's Stealc/Stealga ML model both read it
trivially, and our JSON corpora (sensitive_paths_db.rs,
threat_metrics_windows.rs, etc.) look like classic credential-stealer
reconnaissance to the model. Compressing destroys readable substrings,
XOR breaks magic-byte signature scanners, and `Lazy<String>` decodes once
on first access at runtime.

Output shape: writes TWO files alongside each other:
  <output_stem>.bin   -- the gzip+XOR'd bytes (binary, ~plain/3-5x size)
  <output_stem>.rs    -- a tiny Rust file that include_bytes!()s the .bin

The split lets us obfuscate large fallbacks (vendor_vulns_db.rs is 75 MB
plain, ~15 MB obfuscated) without exploding the source tree -- a hex
byte-array-literal would inflate that to ~90 MB of Rust source.

Usage:
    python3 tools/encode_cloud_fallback.py \\
        <input.json> \\
        <output.rs> \\
        <STATIC_NAME> \\
        [comment]

Example:
    python3 tools/encode_cloud_fallback.py \\
        ../threatmodels/lanscan-sensitive-paths-db.json \\
        src/sensitive_paths_db.rs \\
        SENSITIVE_PATHS_DB \\
        "Built in default sensitive paths db (obfuscated)"

This writes both `src/sensitive_paths_db.rs` (Rust) and
`src/sensitive_paths_db.bin` (raw obfuscated bytes).

Re-run from update-threats.sh / update-asn.sh after each `threatmodels`
fetch. Both the .rs and .bin files belong in the source tree.
"""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

# Must match XOR_KEY in the cloud_model_fallback.rs decoder.
XOR_KEY = 0xA7


def encode(plain_json: bytes) -> bytes:
    """gzip-compress then XOR-encode."""
    compressed = gzip.compress(plain_json, compresslevel=9, mtime=0)
    return bytes(b ^ XOR_KEY for b in compressed)


def format_rust(name: str, comment: str, bin_relpath: str, plain_len: int, obf_len: int) -> str:
    """Render a tiny Rust file that pulls the .bin via include_bytes!."""
    ratio = plain_len / max(1, obf_len)
    return f"""// {comment}
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes in `{bin_relpath}` are gzip-compressed
// (level 9) and XOR-encoded with key 0x{XOR_KEY:02X} so the readable
// JSON content does NOT appear as a literal string in the compiled
// binary. See `src/cloud_model_fallback.rs` for the why and the runtime
// decoder.
//
// Encoded size: {obf_len} bytes (plain: {plain_len}, ratio: {ratio:.2f}x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub {name}: include_bytes!("{bin_relpath}"));
"""


def main(argv: list[str]) -> int:
    if len(argv) < 4:
        print(__doc__, file=sys.stderr)
        return 2
    input_path = Path(argv[1])
    output_rs_path = Path(argv[2])
    name = argv[3]
    comment = argv[4] if len(argv) >= 5 else f"Built in default {name} db (obfuscated)"

    # Co-located .bin file: same stem as the .rs file.
    output_bin_path = output_rs_path.with_suffix(".bin")

    plain = input_path.read_bytes()
    obfuscated = encode(plain)

    output_rs_path.parent.mkdir(parents=True, exist_ok=True)
    output_bin_path.write_bytes(obfuscated)

    rendered = format_rust(name, comment, output_bin_path.name, len(plain), len(obfuscated))
    output_rs_path.write_text(rendered)

    ratio = len(plain) / max(1, len(obfuscated))
    print(
        f"  encoded {input_path.name}: plain {len(plain):,} -> "
        f"obfuscated {len(obfuscated):,} bytes ({ratio:.2f}x) -> "
        f"{output_rs_path.name} + {output_bin_path.name}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
