#!/usr/bin/env python3
"""Generate src/consent_documents_db.rs from the local consent/ snapshot.

Called by update-threats.sh after it copies threatmodels/consent/*.md into
edamame_foundation/consent/. The generated match is the embedded fallback
used when the GitHub raw fetch fails.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONSENT_DIR = ROOT / "consent"
OUT = ROOT / "src" / "consent_documents_db.rs"


def main() -> None:
    files = sorted(p for p in CONSENT_DIR.glob("*.md") if p.is_file())
    if not files:
        print(f"ERROR: no consent markdown under {CONSENT_DIR}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "// Generated by tools/generate_consent_db.py via update-threats.sh.",
        "// Do not edit by hand. Source of truth: ../threatmodels/consent/.",
        "",
        "/// Embedded consent markdown snapshot used when the remote fetch fails.",
        "pub fn embedded_consent(filename: &str) -> Option<&'static str> {",
        "    match filename {",
    ]
    for path in files:
        name = path.name
        if any(ch not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_" for ch in name):
            raise SystemExit(f"unsafe consent filename: {name}")
        raw = path.read_text(encoding="utf-8")
        if not raw.strip():
            raise SystemExit(f"empty consent file: {name}")
        # include_str keeps the snapshot reviewable as sibling markdown.
        rel = f"../consent/{name}"
        lines.append(f'        "{name}" => Some(include_str!("{rel}")),')
    lines.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
            "/// Filenames present in the embedded snapshot.",
            "pub fn embedded_consent_filenames() -> &'static [&'static str] {",
            "    &[",
        ]
    )
    for path in files:
        lines.append(f'        "{path.name}",')
    lines.extend(["    ]", "}", ""])
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(files)} documents)")


if __name__ == "__main__":
    main()
