// Generated by tools/generate_consent_db.py via update-threats.sh.
// Do not edit by hand. Source of truth: ../threatmodels/consent/.

/// Embedded consent markdown snapshot used when the remote fetch fails.
pub fn embedded_consent(filename: &str) -> Option<&'static str> {
    match filename {
        "compliance-scanner-EN.md" => Some(include_str!("../consent/compliance-scanner-EN.md")),
        "compliance-scanner-FR.md" => Some(include_str!("../consent/compliance-scanner-FR.md")),
        "privacy-LLM-EN.md" => Some(include_str!("../consent/privacy-LLM-EN.md")),
        "privacy-LLM-FR.md" => Some(include_str!("../consent/privacy-LLM-FR.md")),
        "privacy-detailed-Android-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-Android-EN.md"))
        }
        "privacy-detailed-Android-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-Android-FR.md"))
        }
        "privacy-detailed-Linux-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-Linux-EN.md"))
        }
        "privacy-detailed-Linux-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-Linux-FR.md"))
        }
        "privacy-detailed-Windows-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-Windows-EN.md"))
        }
        "privacy-detailed-Windows-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-Windows-FR.md"))
        }
        "privacy-detailed-ai-Linux-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-Linux-EN.md"))
        }
        "privacy-detailed-ai-Linux-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-Linux-FR.md"))
        }
        "privacy-detailed-ai-Windows-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-Windows-EN.md"))
        }
        "privacy-detailed-ai-Windows-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-Windows-FR.md"))
        }
        "privacy-detailed-ai-macOS-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-macOS-EN.md"))
        }
        "privacy-detailed-ai-macOS-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-ai-macOS-FR.md"))
        }
        "privacy-detailed-iOS-EN.md" => Some(include_str!("../consent/privacy-detailed-iOS-EN.md")),
        "privacy-detailed-iOS-FR.md" => Some(include_str!("../consent/privacy-detailed-iOS-FR.md")),
        "privacy-detailed-macOS-EN.md" => {
            Some(include_str!("../consent/privacy-detailed-macOS-EN.md"))
        }
        "privacy-detailed-macOS-FR.md" => {
            Some(include_str!("../consent/privacy-detailed-macOS-FR.md"))
        }
        "profiling-feedback-EN.md" => Some(include_str!("../consent/profiling-feedback-EN.md")),
        "profiling-feedback-FR.md" => Some(include_str!("../consent/profiling-feedback-FR.md")),
        "request-report-EN.md" => Some(include_str!("../consent/request-report-EN.md")),
        "request-report-FR.md" => Some(include_str!("../consent/request-report-FR.md")),
        "user-feedback-EN.md" => Some(include_str!("../consent/user-feedback-EN.md")),
        "user-feedback-FR.md" => Some(include_str!("../consent/user-feedback-FR.md")),
        "vulnerability-feedback-EN.md" => {
            Some(include_str!("../consent/vulnerability-feedback-EN.md"))
        }
        "vulnerability-feedback-FR.md" => {
            Some(include_str!("../consent/vulnerability-feedback-FR.md"))
        }
        _ => None,
    }
}

/// Filenames present in the embedded snapshot.
pub fn embedded_consent_filenames() -> &'static [&'static str] {
    &[
        "compliance-scanner-EN.md",
        "compliance-scanner-FR.md",
        "privacy-LLM-EN.md",
        "privacy-LLM-FR.md",
        "privacy-detailed-Android-EN.md",
        "privacy-detailed-Android-FR.md",
        "privacy-detailed-Linux-EN.md",
        "privacy-detailed-Linux-FR.md",
        "privacy-detailed-Windows-EN.md",
        "privacy-detailed-Windows-FR.md",
        "privacy-detailed-ai-Linux-EN.md",
        "privacy-detailed-ai-Linux-FR.md",
        "privacy-detailed-ai-Windows-EN.md",
        "privacy-detailed-ai-Windows-FR.md",
        "privacy-detailed-ai-macOS-EN.md",
        "privacy-detailed-ai-macOS-FR.md",
        "privacy-detailed-iOS-EN.md",
        "privacy-detailed-iOS-FR.md",
        "privacy-detailed-macOS-EN.md",
        "privacy-detailed-macOS-FR.md",
        "profiling-feedback-EN.md",
        "profiling-feedback-FR.md",
        "request-report-EN.md",
        "request-report-FR.md",
        "user-feedback-EN.md",
        "user-feedback-FR.md",
        "vulnerability-feedback-EN.md",
        "vulnerability-feedback-FR.md",
    ]
}
