// Built in default CVE detection params db (obfuscated)
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes in `cve_detection_params_db.bin` are gzip-compressed
// (level 9) and XOR-encoded with key 0xA7 so the readable
// JSON content does NOT appear as a literal string in the compiled
// binary. See `src/cloud_model_fallback.rs` for the why and the runtime
// decoder.
//
// Encoded size: 3014 bytes (plain: 11993, ratio: 3.98x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub CVE_DETECTION_PARAMS_DB: include_bytes!("cve_detection_params_db.bin"));
