on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Setup EDAMAME Posture
        uses: edamametechnologies/edamame_posture_action@v0.3.83
        with:
          edamame_user: ${{ secrets.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ secrets.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}

      - uses: actions/checkout@v3

      - run: |
          # Install protobuf
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install rustfmt
        run: |
          rustup component add rustfmt

      - name: Check code format
        run: |
          cargo fmt --all -- --check
